Added hacks to work around an annoying xgettext bug

diff --git a/devel-tools/buildpot b/devel-tools/buildpot
--- a/devel-tools/buildpot
+++ b/devel-tools/buildpot
@@ -6,7 +6,20 @@ echo -n "Building po/dayplanner.pot..."
 YEAR="`date +%Y`"
 echo -n "."
 # Create the pot-file
-xgettext --copyright-holder 'Eskild Hustvedt' --msgid-bugs-address 'https://gna.org/bugs/?group=dayplanner' -o ./po/dayplanner.pot --keyword --keyword=DP_gettext -d dayplanner --add-comments="TRANSLATORS" --language perl ./dayplanner ./dayplanner-notifier
+POTGEN="dayplanner_pot_gen_tmp_$$_$RANDOM_$YEAR.tmpdir"
+if ! mkdir -p $POTGEN; then
+       echo "Unable to create the $POTGEN directory!"
+       exit 1
+fi
+cd $POTGEN
+cp ../dayplanner .
+cp ../dayplanner-notifier .
+# This works around an damned annoying bug in xgettext when using --keyword=DP_gettext.
+# Changing it to just gettext allows us to use the default, which isn't broken.
+perl -pi -e 's#gettext\(\@\_\)#BUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUG#g;s#DP_gettext#gettext(#g' ./dayplanner ./dayplanner-notifier
+xgettext --copyright-holder 'Eskild Hustvedt' --msgid-bugs-address 'https://gna.org/bugs/?group=dayplanner' -o ../po/dayplanner.pot -d dayplanner --add-comments="TRANSLATORS" --language perl ./dayplanner ./dayplanner-notifier
+cd ..
+rm -rf $POTGEN
 echo -n "."
 # Fix the headers using perl
 perl -pi -e "s%^# SOME DESCRIPTIVE TITLE.%# PO file for Day Planner%g;
@@ -14,5 +27,4 @@ s%^# This file is distributed under the same license as the PACKAGE package.%# T
 s%^(#.+) YEAR %\$1 $YEAR %g" ./po/dayplanner.pot
 echo -n "."
 cd ..
-rm -rf $TEMPDIR
 echo "done"
